export const COUNTRIES: string[] = [
  'Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre', 'Angola',
  'Arabie Saoudite', 'Argentine', 'Arménie', 'Australie', 'Autriche', 'Azerbaïdjan',
  'Bahreïn', 'Bangladesh', 'Belgique', 'Belize', 'Bénin', 'Bhoutan', 'Biélorussie',
  'Bolivie', 'Bosnie-Herzégovine', 'Botswana', 'Brésil', 'Brunei', 'Bulgarie',
  'Burkina Faso', 'Burundi', 'Cambodge', 'Cameroun', 'Canada', 'Chili', 'Chine', 'Chypre',
  'Colombie', 'Costa Rica', 'Côte d\'Ivoire', 'Croatie', 'Cuba', 'Danemark',
  'Égypte', 'Émirats Arabes Unis', 'Équateur', 'Espagne', 'Estonie', 'États-Unis',
  'Éthiopie', 'Fidji', 'Finlande', 'France', 'Gabon', 'Géorgie', 'Ghana', 'Grèce',
  'Guatemala', 'Guinée', 'Guyana', 'Haïti', 'Honduras', 'Hongrie', 'Île Maurice',
  'Inde', 'Indonésie', 'Irak', 'Iran', 'Irlande', 'Islande', 'Israël', 'Italie',
  'Jamaïque', 'Japon', 'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizstan', 'Kosovo',
  'Koweït', 'Laos', 'Lettonie', 'Liban', 'Liberia', 'Libye', 'Lituanie', 'Luxembourg',
  'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Maldives', 'Mali', 'Malte', 'Maroc',
  'Mauritanie', 'Mexique', 'Moldavie', 'Monaco', 'Mongolie', 'Monténégro', 'Mozambique',
  'Myanmar', 'Namibie', 'Népal', 'Nicaragua', 'Niger', 'Nigeria', 'Norvège',
  'Nouvelle-Zélande', 'Oman', 'Ouganda', 'Ouzbékistan', 'Pakistan', 'Panama',
  'Papouasie-Nouvelle-Guinée', 'Paraguay', 'Pays-Bas', 'Pérou', 'Philippines',
  'Pologne', 'Portugal', 'Qatar', 'République Dominicaine', 'République Tchèque',
  'Roumanie', 'Royaume-Uni', 'Russie', 'Rwanda', 'Salvador', 'Sénégal', 'Serbie',
  'Sierra Leone', 'Singapour', 'Slovaquie', 'Slovénie', 'Soudan', 'Sri Lanka',
  'Suède', 'Suisse', 'Suriname', 'Syrie', 'Tadjikistan', 'Taïwan', 'Tanzanie',
  'Thaïlande', 'Timor Oriental', 'Togo', 'Tunisie', 'Turkménistan', 'Turquie',
  'Ukraine', 'Uruguay', 'Venezuela', 'Vietnam', 'Yémen', 'Zambie', 'Zimbabwe',
].sort((a, b) => a.localeCompare(b, 'fr'))
